# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# GH actions.
# We use it to cover windows and mac builds
# Jenkins is still the primary CI

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: CI-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  Android:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build TVM
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          ../tests/scripts/task_config_build_jvm.sh .
          cmake ..
          make runtime -j4          
      - name: Build TVM4J
        run: |
          make jvmpkg
      - name: Build android_rpc
        working-directory: apps/android_rpc
        run: |
          set -eux
          export PATH="${ANDROID_NDK_LATEST_HOME}:$PATH"
          gradle clean build
      - name: Upload android_rpc APK
        uses: actions/upload-artifact@v2
        with:
          name: android_rpc-debug.apk
          path: ./apps/android_rpc/app/build/outputs/apk/debug/app-debug.apk
      - name: Build android_deploy
        working-directory: apps/android_deploy
        run: |
          set -eux
          export PATH="${ANDROID_NDK_LATEST_HOME}:$PATH"
          gradle clean build
      - name: Upload android_deploy APK
        uses: actions/upload-artifact@v2
        with:
          name: android_deploy-debug.apk
          path: ./apps/android_deploy/app/build/outputs/apk/debug/app-debug.apk
      - name: Build android_camera
        working-directory: apps/android_camera
        run: |
          export TVM_HOME=~/work/tvm/tvm
          export PYTHONPATH=$TVM_HOME/python:${PYTHONPATH}
          set -eux
          mkdir -p app/src/main/assets/models/
          export TVM_NDK_CC=${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
          python3 ${TVM_HOME}/python/gen_requirements.py
          pip3 install -r ${TVM_HOME}/python/requirements/core.txt
          cd models
          pip3 install -r requirements.txt
          python3 prepare_model.py
          cd ..
          export PATH="${ANDROID_NDK_LATEST_HOME}:$PATH"
          gradle clean build
      - name: Upload android_camera APK
        uses: actions/upload-artifact@v2
        with:
          name: android_camera-debug.apk
          path: ./apps/android_camera/app/build/outputs/apk/debug/app-debug.apk
